-- Create chat_interactions table
CREATE TABLE IF NOT EXISTS public.chat_interactions (
  id BIGSERIAL PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  user_message TEXT NOT NULL,
  ai_response TEXT NOT NULL,
  metadata JSONB,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Add comments
COMMENT ON TABLE public.chat_interactions IS 'Stores chat interactions between users and the AI assistant';
COMMENT ON COLUMN public.chat_interactions.user_id IS 'Reference to the user who initiated the interaction';
COMMENT ON COLUMN public.chat_interactions.user_message IS 'The message sent by the user';
COMMENT ON COLUMN public.chat_interactions.ai_response IS 'The response generated by the AI';
COMMENT ON COLUMN public.chat_interactions.metadata IS 'Additional metadata about the interaction (model used, tokens, etc.)';

-- Create indexes for better query performance
CREATE INDEX IF NOT EXISTS idx_chat_interactions_user_id ON public.chat_interactions(user_id);
CREATE INDEX IF NOT EXISTS idx_chat_interactions_created_at ON public.chat_interactions(created_at);

-- Enable Row Level Security
ALTER TABLE public.chat_interactions ENABLE ROW LEVEL SECURITY;

-- Create RLS policies
CREATE POLICY "Users can view their own chat interactions" 
  ON public.chat_interactions 
  FOR SELECT 
  USING (auth.uid() = user_id);

CREATE POLICY "Users can insert their own chat interactions" 
  ON public.chat_interactions 
  FOR INSERT 
  WITH CHECK (auth.uid() = user_id);

-- Create a function to update the updated_at column
CREATE OR REPLACE FUNCTION public.update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Create a trigger to update the updated_at column on each update
CREATE TRIGGER update_chat_interactions_updated_at
BEFORE UPDATE ON public.chat_interactions
FOR EACH ROW
EXECUTE FUNCTION public.update_updated_at_column();

-- Grant necessary permissions
GRANT SELECT, INSERT, UPDATE, DELETE 
  ON public.chat_interactions 
  TO authenticated_user, service_role;

GRANT USAGE, SELECT 
  ON SEQUENCE public.chat_interactions_id_seq 
  TO authenticated_user, service_role;
